on:
  push:
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: clone repository
        uses: actions/checkout@v3
      - run: ls
      - name: build docker image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aditirvan/container-batch-11:${{ github.run_number }}
