on:
  push:
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: clone repository
        uses: actions/checkout@v3
      - run: ls
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aditirvan/container-batch-11:${{ github.run_number }}
      - name: check image
        run: docker images
